spring.application.name=elib-gateway
server.port=5551

spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:5550
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/user/**
spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=2

spring.cloud.gateway.mvc.routes[1].id=auth-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:5550
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.mvc.routes[1].filters[0]=StripPrefix=2

spring.cloud.gateway.mvc.routes[2].id=book-catalogue-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:5552
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/book-catalogue/**
spring.cloud.gateway.mvc.routes[2].filters[0]=StripPrefix=2

spring.cloud.gateway.mvc.routes[3].id=book-lending-service
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:5553
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/book-lending/**
spring.cloud.gateway.mvc.routes[3].filters[0]=StripPrefix=2

spring.cloud.gateway.mvc.routes[4].id=book-club-service
spring.cloud.gateway.mvc.routes[4].uri=http://localhost:5554
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/book-club/**
spring.cloud.gateway.mvc.routes[4].filters[0]=StripPrefix=2
