services:

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  elib-identity:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: elib-identity
    ports:
      - "9921:9921"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 9921
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/mydb?currentSchema=identity
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

  elib-catalogue:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: elib-catalogue
    ports:
      - "9922:9922"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 9922
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/mydb?currentSchema=catalogue
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

  elib-lending:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: elib-lending
    ports:
      - "9923:9923"
    depends_on:
      postgres:
        condition: service_healthy
      elib-catalogue:
        condition: service_started
    environment:
      SERVER_PORT: 9923
      CATALOGUE_SERVICE_URL: http://elib-catalogue:9922
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/mydb?currentSchema=lending
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

  elib-notification:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: elib-notification
    ports:
      - "9924:9924"
    environment:
      SERVER_PORT: 9924

  elib-bookclub:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: elib-bookclub
    ports:
      - "9925:9925"
    environment:
      SERVER_PORT: 9925

  elib-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: elib-gateway
    ports:
      - "9920:9920"
    depends_on:
      - elib-identity
      - elib-catalogue
      - elib-lending
      - elib-notification
      - elib-bookclub
    environment:
      SERVER_PORT: 9920
      IDENTITY_SERVICE_URL: http://elib-identity:9921
      CATALOGUE_SERVICE_URL: http://elib-catalogue:9922
      LENDING_SERVICE_URL: http://elib-lending:9923
      NOTIFICATION_SERVICE_URL: http://elib-notification:9924
      BOOKCLUB_SERVICE_URL: http://elib-bookclub:9925

volumes:
  postgres_data:
