spring.application.name=elib-discovery
server.port=8761

# This is the server itself - don't register with itself or fetch its own registry
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.wait-time-in-ms-when-sync-empty=0
